user_prompt="A beautiful black hair girl with her eyes closed in champagne long sleeved formal dress standing in her bright room with delicate blue vases with pink roses on the left and some white roses, filled with upgraded growth all around on the right."
version_number=0
api_key='FVObatuUKrwbktgmyhlCFLQxiAreiNaC'
use_gpt=True
height=1024
width=1024
use_base=True
base_ratio=0.1
cfg=7
layer_data='/pyy/yuyang_blob/pyy/code/RPG-DiffusionMaster/inference/images_100_autocaption_34b-newer.json'
lora_path="/pyy/yuyang_blob/pyy/code/diffusers/examples/text_to_image/output/shape_lora/checkpoint-1"
